"""make_fecha_nullable

Revision ID: 04d8ebaa9afe
Revises: f2367ce54497
Create Date: 2026-06-08 13:30:06.156329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d8ebaa9afe'
down_revision: Union[str, Sequence[str], None] = 'f2367ce54497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('civil_work', 'fecha',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('civil_work', 'fecha',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
