"""adding_civil_works_tables

Revision ID: f2367ce54497
Revises: 3b6c3f0f1e96
Create Date: 2026-06-06 13:51:52.453997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2367ce54497'
down_revision: Union[str, Sequence[str], None] = '3b6c3f0f1e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excel_upload',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('id_user', sa.Integer(), nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=True),
        sa.Column('file_url', sa.String(length=500), nullable=True),
        sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_excel_upload_id_user'), 'excel_upload', ['id_user'], unique=False)
    op.create_index(op.f('ix_excel_upload_uploaded_at'), 'excel_upload', ['uploaded_at'], unique=False)

    op.create_table('civil_work',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('id_upload', sa.Integer(), nullable=False),
        sa.Column('numero_trabajo', sa.Integer(), nullable=False),
        sa.Column('semana', sa.Integer(), nullable=True),
        sa.Column('fecha', sa.Date(), nullable=False),
        sa.Column('contratista', sa.String(length=150), nullable=False),
        sa.Column('detalle_trabajos', sa.String(length=500), nullable=True),
        sa.Column('tipo_trabajo', sa.String(length=100), nullable=False),
        sa.Column('forma_pago', sa.String(length=100), nullable=False),
        sa.Column('agenda_tipo_levantamiento', sa.String(length=150), nullable=True),
        sa.Column('zonal', sa.String(length=100), nullable=False),
        sa.Column('localidad', sa.String(length=100), nullable=False),
        sa.Column('region', sa.String(length=100), nullable=False),
        sa.Column('edificio_instalacion', sa.String(length=150), nullable=True),
        sa.Column('estado_trabajos', sa.String(length=50), nullable=False),
        sa.Column('factura', sa.String(length=100), nullable=True),
        sa.Column('hh', sa.String(length=50), nullable=True),
        sa.Column('monto_neto', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('monto_hh', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.ForeignKeyConstraint(['id_upload'], ['excel_upload.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_civil_work_contratista'), 'civil_work', ['contratista'], unique=False)
    op.create_index(op.f('ix_civil_work_estado_trabajos'), 'civil_work', ['estado_trabajos'], unique=False)
    op.create_index(op.f('ix_civil_work_fecha'), 'civil_work', ['fecha'], unique=False)
    op.create_index(op.f('ix_civil_work_id_upload'), 'civil_work', ['id_upload'], unique=False)
    op.create_index(op.f('ix_civil_work_numero_trabajo'), 'civil_work', ['numero_trabajo'], unique=False)
    op.create_index(op.f('ix_civil_work_region'), 'civil_work', ['region'], unique=False)
    op.create_index(op.f('ix_civil_work_tipo_trabajo'), 'civil_work', ['tipo_trabajo'], unique=False)
    op.create_index(op.f('ix_civil_work_zonal'), 'civil_work', ['zonal'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_civil_work_zonal'), table_name='civil_work')
    op.drop_index(op.f('ix_civil_work_tipo_trabajo'), table_name='civil_work')
    op.drop_index(op.f('ix_civil_work_region'), table_name='civil_work')
    op.drop_index(op.f('ix_civil_work_numero_trabajo'), table_name='civil_work')
    op.drop_index(op.f('ix_civil_work_id_upload'), table_name='civil_work')
    op.drop_index(op.f('ix_civil_work_fecha'), table_name='civil_work')
    op.drop_index(op.f('ix_civil_work_estado_trabajos'), table_name='civil_work')
    op.drop_index(op.f('ix_civil_work_contratista'), table_name='civil_work')

    op.drop_table('civil_work')

    op.drop_index(op.f('ix_excel_upload_uploaded_at'), table_name='excel_upload')
    op.drop_index(op.f('ix_excel_upload_id_user'), table_name='excel_upload')

    op.drop_table('excel_upload')
    # ### end Alembic commands ###
